POST https://node-zero-w4ml.onrender.com/videos
Content-Type: application/json

# {
#   "title": "Video 01",
#   "description": "Esse é o vídeo 01",
#   "duration": 180
# },
# {
#   "title": "Video node",
#   "description": "Esse é o vídeo node",
#   "duration": 180
# },
{
  "title": "Video Node 3 ",
  "description": "Esse é o vídeo 03",
  "duration": 180
}

###

GET https://node-zero-w4ml.onrender.com/videos

###

PUT https://node-zero-w4ml.onrender.com/f2e5888b-8586-4b56-9a9b-80507294c41d
Content-Type: application/json

{
  "title": "Video node 1",
  "description": "Esse é o vídeo 01",
  "duration": 190
}

###

DELETE  http://localhost:3333/videos/